### ISSUE TITLE
Misleading docs on determining lemma structure

### ISSUE THREAD

**Issue by Karryanna** [ufal/morphodita#11]
Me again. Some time ago, I got quite confused by the API reference at ÚFAL, which, regarding parts of lemma structure, states: 

> These parts are stored in one string and the boundaries between them can be determined by morpho::raw_lemma_len and morpho::lemma_id_len methods.

Given that on PyPI, it says

> The bindings is a straightforward conversion of the C++ bindings API.

I had some hard time finding out why there's no lemma_id_len function on Morpho.

I have to admit that especially on PyPI, it shows C++ API as providing the rawLemma and lemmaId function, and the same can be seen in 'C++ Bindings API' section in ÚFAL API reference but still I find this quite misleading.

Perhaps there would be a way to clarify this?

**Comment by foxik** [comment]
Yep, the documentation of the Python API is non-existent. There are plans to improve the situation, but in a different package, so I am just closing this -- but feel free to create a pull request if you are motivated enough ;-)
