### ISSUE TITLE
Request - error reporting on model load failure

### ISSUE THREAD

**Issue by Karryanna** [ufal/morphodita#12]
Me one more time, but if nothing else, by this I run out of issues I already have :)
Also, this one is not a bug, rather a feature/improvement request.

I understand that model load may fail (for example because the user provides path which does not lead to a valid model file) and it is the user's responsibility to check if this didn't happen.
However, I wonder whether an exception could be raised in such case. To me, this feels less error-prone and making it easier to locate the error (esp. if the exception would give some details, like 'file is not found' or 'file not valid model').

**Comment by foxik** [comment]
The only bit (success/failure) is definitely suboptimal -- but as currently implemented, the C++ API does not offer more. When there will be API change (with a new major version), I will take it into account and offer some additional error code...
