### ISSUE TITLE
Installation of Python bindings fails on Python 3.8

### ISSUE THREAD

**Issue by dlukes** [ufal/morphodita#13]
The compilation error is:

```
morphodita/morphodita_python.cpp:3321:3: error: use of undeclared identifier '_PyObject_GC_UNTRACK'
      _PyObject_GC_UNTRACK(descr);
      ^
```

I guess this is caused by the fact that versions of SWIG prior to August 2019 did not support Python 3.8 (cf. <http://www.swig.org/>)? If so, would you please consider doing a new release of the Python bindings on PyPI using this new version of SWIG?

**Comment by foxik** [comment]
Yup, it is. We already released a new version of UDPipe (and I set up infrastructure for building binary wheels). So I hope to make a new release "soon" (sometimes in the next week or the one after it, because there are other issues I want to take care of). Leaving open as a remainder.

**Comment by dlukes** [comment]
Perfect, thanks :)

> I set up infrastructure for building binary wheels

Great!

**Comment by foxik** [comment]
This took much longer than I hoped, but the new version including support for Python 3.8 and with binary wheels for all platforms has been released.
