### ISSUE TITLE
Add a more reproducible example of how to use this model in python

### ISSUE THREAD

**Issue by tomasj-ds** [ufal/morphodita#18]
Hi,

it is possible to create a more detailed example of how to use this model/module with python? I am not able to 100% understand how to work with `tagger = Tagger.load(sys.argv[1])`.  Can you provide a more detailed example? thanks.

**Comment by dlukes** [comment]
You might be interested in [this wrapper library I wrote](https://corpy.readthedocs.io/en/stable/guides/morphodita.html). It's due for an overhaul to make it more type-checking friendly, but it should be usable as is.

**Comment by foxik** [comment]
Closing, but contributions are still welcome :-)
