### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by vladob54** [ufal/morphodita#2]
Dear Colleague,

I could quite appreciate having also a slightly modified MorphoDiTa imput mode: vertical with XML tags for documents, paragraphs, sentences, etc. For example:

```
<doc title="Hamlet">
<p>
<s>
To
be
or 
not
to
be
<g/>
,
that
is
a
question
<g/>
.
</s>
</p>
</doc>
```

Within this mode, the tagger would simply ignore all XML markup, I could also use the `<s>` tags as end-of-sentence markers to improve the accuracy around punctuation.

I believe that this would not be difficult to implement :-)

Best,

Vlado B, 19:45

**Comment by foxik** [comment]
While working on Korektor, I have been considering following two formats:
- vertical format allowing "ignored" entries -- if a line starts (for example) by tab character, the rest of the line is just ignored and copied to output. This allows embedding any data to vertical format (both spaces and additional markup like XML). So your example would work, if the XML markup was preceeded by a tab character (and an empty line was added before `</s>` so indicate end of sentence).
- generic XML format -- elements and attributes would be ignored and copied to output. I imagined that the user could specify elements marking tokens and elements marking sentences (and if some of them would not be specified, the tokenizer/segmenter would be used). There is a slight technical problem here -- MorphoDiTa currently assumes the tokens are subsequences of the input, which would not be the case here -- the `&amp;` and `&lt;` entities in the input must be replaced. But currently MorphoDiTa does not have generic `InputFormat` class anyway (which will be added in next version), so this can be dealt with when designing the `InputFormat` class (most probably by allowing the `InputFormat` class to return "decoded" input in addition to the tokens, which would be subsequences of the "decoded" input and not the original input)

My work plans are currently to finish Korektor, then deal with TrEd and then work on MorphoDiTa, so the generic `InputFormat` class will be done sometimes in summer. But if you need this soon, I could hack the vertical format with ignored entries if it would be enought for you -- are you using the `run_...` binary or some language binding?

**Comment by vladob54** [comment]
Dear Milan,
    
    
      While working on Korektor, I have been considering following
        two formats:
      
        vertical format allowing "ignored" entries -- if a line
          starts (for example) by tab character, the rest of the line is
          just ignored and copied to output. This allows embedding any
          data to vertical format (both spaces and additional markup
          like XML). So your example would work, if the XML markup was
          preceeded by a tab character (and an empty line was added
          before </s> so indicate end of sentence).
      
    
    
    Yes, the empty line convention is in the manual, but the leading tab
    is not.  You may want to add ;-)  
    
    
      
        generic XML format -- elements and attributes would be
          ignored and copied to output. I imagined that the user could
          specify elements marking tokens and elements marking sentences
          (and if some of them would not be specified, the
          tokenizer/segmenter would be used). There is a slight
          technical problem here -- MorphoDiTa currently assumes the
          tokens are subsequences of the input, which would not be the
          case here -- the &amp; and &lt;
          entities in the input must be replaced. But currently
          MorphoDiTa does not have generic InputFormat
          class anyway (which will be added in next version), so this
          can be dealt with when designing the InputFormat
          class (most probably by allowing the InputFormat
          class to return "decoded" input in addition to the tokens,
          which would be subsequences of the "decoded" input and not the
          original input)
      
      My work plans are currently to finish Korektor, then deal with
        TrEd and then work on MorphoDiTa, so the generic InputFormat
        class will be done sometimes in summer. But if you need this
        soon, I could hack the vertical format with ignored entries if
        it would be enought for you -- are you using the run_...
        binary or some language binding?
      
    
    
    OK, I'll wait :-)
    
    I am missing one more feature: an explicit indication that a token
    was not found in the morphological dictionary.  If, e.g., an English
    expression appears in the text:
    
    Pod     pod     RR--7----------
    hlavičkou       hlavička        NNFS7-----A----
    Roadrunner      Roadrunner      AAXXX----1A----
    records record  NNIPX-----A----
    vyšlo   vyjít   VpNS---XR-AA---
    v       v       RR--6----------
    roce    rok     NNIS6-----A---1
    1989    1989    C=-------------
    album   album   NNNS1-----A----
    Beneath Beneath AAXXX----1A----
    The     the     AAXXX----1A----
    Remains Remains NNMPX-----A----
    <g/>
    ,       ,       Z:-------------
    které   který   P4NS1----------
    bylo    být     VpNS---XR-AA---
    následováno     následovat      VsNS---XX-AP---
    dlouhým dlouhý  AANS7----1A----
    evropským       evropský        AANS7----1A----
    turné   turné   NNNXX-----A----
    <g/>
    .       .       Z:-------------
    
    I would not expect that "the" be tagged as adjective...
    
    Best regards,
    
    Vlado B, 12:05
    -- 
Vladimír Benko

Slovak Academy of Sciences
Ľ. Štúr Institute of Linguistics
Panská 26, SK-81101 Bratislava

Tel +421-2-54431762  Fax -54431756

**Comment by foxik** [comment]
> Yes, the empty line convention is in the manual, but the leading tab is not.  You may want to add ;-)  

This is just a plan -- it is not implemented yet (that is why it is not in the manual).

> OK, I'll wait :-)

The complete `InputFormat` redesign will take some time, but if it would help you, I could do the "vertical with ignored lines" hack soon-ish.

> I am missing one more feature: an explicit indication that a token was not found in the morphological dictionary.  If, e.g., an English expression appears in the text:

That is a common feature request, but it is unfortunately missing in the API (it will be in 2.0; it was not present in 1.* on purpose for a different reason). Are you using the `run_tagger` binary? If so, I can add the "turn off the guesser" feature, so you would see the `X:-------------` tags for unknown words. If you are using the API directly, you have to explicitly ask the dictionary if the sentence words are known or not; 2.0 version will make it possible to forbid the morphological guesser.

**Comment by vladob54** [comment]
Milan,
      
    
    The complete InputFormat redesign will
      take some time, but if it would help you, I could do the "vertical
      with ignored lines" hack soon-ish.
    
    No, it is not that urgent.  Though it might be interesting to see,
    whether the precision improves around tags, if they are ignored by
    the tagger.
    
    That is a common feature request, but it is
      unfortunately missing in the API (it will be in 2.0; it was not
      present in 1.* on purpose for a different reason). Are you using
      the run_tagger binary? If so, I can add the "turn
      off the guesser" feature, so you would see the X:-------------
      tags for unknown words. If you are using the API directly, you
      have to explicitly ask the dictionary if the sentence words are
      known or not; 2.0 version will make it possible to forbid the
      morphological guesser.
    
    Yes, the possibility of turning out the guesser might be useful. 
    But having an extra flag indicating the success level of the
    morphological analysis would be even better.  Something like that
    has been implemented by Radovan Garabík in for the Slovak National
    Corpus: the value is either a number (level of ambiguity), or "XX"
    meaning that the particular token has not been found in the
    dictionary and the corresponding lemma has been guessed :-)
    
    BTW, I have just indexed the (smaller version) of the Czech web
    corpus.  You can try it here (Via Guest Access):
    
    http://ucts.uniba.sk/
    
    Best,
    
    Vlado B, 16:20 
    
    -- 
Vladimír Benko

Slovak Academy of Sciences
Ľ. Štúr Institute of Linguistics
Panská 26, SK-81101 Bratislava

Tel +421-2-54431762  Fax -54431756

**Comment by foxik** [comment]
Closing, as this will be done differently in the future.
