### ISSUE TITLE
Inconsistency in result_object

### ISSUE THREAD

**Issue by martcernycsob** [ufal/morphodita#21]
Following https://github.com/ufal/morphodita/issues/20
http://lindat.mff.cuni.cz/services/morphodita/api/tag?output=json&model=czech-morfflex&data=.4.+&guesser=no returns `spaces` parameter
AND
 https://lindat.mff.cuni.cz/services/morphodita/api/tag?output=json&model=czech-morfflex&data=4+5&guesser=no returns `space` parameter
I see the issue in the implementation, not in docs.

**Comment by foxik** [comment]
Thanks! I have just pushed a fix and the LINDAT service has been upgraded.
