### ISSUE TITLE
Tokens lost when splitting long sentences

### ISSUE THREAD

**Issue by dlukes** [ufal/morphodita#6]
Sorry for being so hung up on tokenization, but I think I've come across another minor bug. Unfortunately, it seems to be related to the sentence-splitting of extremely long sentences, so I haven't found a nice and clean way to reproduce it other than using [this monster](https://gist.githubusercontent.com/dlukes/ad3f99a079641855f028fa8ba1ea68e2/raw/63b77c35010e860474dc277ed9f90a59381ca90a/sample.txt) as input. Without further ado:

```sh
$ wget https://gist.githubusercontent.com/dlukes/ad3f99a079641855f028fa8ba1ea68e2/raw/63b77c35010e860474dc277ed9f90a59381ca90a/sample.txt
```

Now look for the following pattern, which occurs only once in the file:

```sh
$ grep -o '(21:47 DEedhCjlyt :0 YQTxWzFwPQ  DEedhCjlyt 8) YQTxWzFwPQ  49)' sample.txt
(21:47 DEedhCjlyt :0 YQTxWzFwPQ  DEedhCjlyt 8) YQTxWzFwPQ  49)
```

Notice that there is `:0` roughly at the end of the first quarter of the substring. Now if I tokenize the file using MorphoDiTa d9e7b78 and paste the tokens back together, the `0` is gone:

```sh
$ /path/to/md/master/run_tokenizer --tokenizer=czech --output=vertical sample.txt | tail -n+2837 | head -n14 | paste -sd" "
( 21 : 47 DEedhCjlyt :  YQTxWzFwPQ DEedhCjlyt 8 ) YQTxWzFwPQ 49 )
```

Whereas if I do the same thing using MorphoDiTa stable (1.3), it is preserved:

```sh
$ /path/to/md/stable/run_tokenizer --tokenizer=czech --output=vertical sample.txt | tail -n+2838 | head -n14 | paste -sd" "
( 21 :  47 DEedhCjlyt : 0 YQTxWzFwPQ DEedhCjlyt 8 ) YQTxWzFwPQ 49
```

Admittedly, this is very unusual input, but more "conventional" long sentences will probably be affected by this as well, won't they?

**Comment by foxik** [comment]
Thanks for noticing the problem and reporing it! It is very pleasant to fix bugs with existing test cases :-)

**Comment by dlukes** [comment]
My pleasure and thanks fot the quick fix! :)
